### ISSUE TITLE
Work with Mamba?

### ISSUE THREAD

**Issue by AniAggarwal** [Anaconda-Platform/nb_conda_kernels#250] opened 2024-03-04 16:27 UTC
Is there a way to make this package work with mamba (specifically micromamba) instead of conda?
I get the following error and my envs don't show up unless manually installed.
```log
[E 2024-03-04 11:20:04.378 ServerApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
```

**Comment by mcg1969** [comment] 2024-03-05 17:45
This is a duplicate of #234; so I'm going to close it, but not for negative reasons.

**Closed by mcg1969** 2024-03-05 17:45 UTC

**Comment by AniAggarwal** [comment] 2024-03-05 17:57
No idea how I didn't find that issue before making this one. Thanks for taking a look.

**Comment by mcg1969** [comment] 2024-03-05 17:58
No worries at all.
