### ISSUE TITLE
Weird failure on conda create tied to pyzmq and constants.so

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_conda_kernels#26] opened 2016-06-03 17:48 UTC
When I execute this command, `nb_conda_kernels` causes a weird `pyzmq` error apparently tied to `constants.so`.  I updated `pyzmq` (only change was build number) but problem persisted:

```
$ conda create -n mro -c mro -c r -c anaconda-nb-extensions jupyter notebook  nb_conda nb_conda_kernels rpy2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...............
Solving package specifications .............

Package plan for installation in environment /Users/ijstokes/anaconda/envs/mro:

The following NEW packages will be INSTALLED:

    appnope:            0.1.0-py27_0                             
    backports:          1.0-py27_0                               
    backports_abc:      0.4-py27_0                               
    configparser:       3.5.0b2-py27_1                           
    decorator:          4.0.9-py27_0                             
    entrypoints:        0.2-py27_1                               
    freetype:           2.5.5-0                                  
    functools32:        3.2.3.2-py27_0                           
    get_terminal_size:  1.0.0-py27_0                             
    ipykernel:          4.3.1-py27_0                             
    ipython:            4.2.0-py27_1                             
    ipython_genutils:   0.1.0-py27_0                             
    ipywidgets:         4.1.1-py27_0                             
    jbig:               2.1-0                                    
    jinja2:             2.8-py27_1                               
    jpeg:               8d-2               r                     
    jsonschema:         2.5.1-py27_0                             
    jupyter:            1.0.0-py27_2                             
    jupyter_client:     4.2.2-py27_0                             
    jupyter_console:    4.1.1-py27_0                             
    jupyter_core:       4.1.0-py27_0                             
    libgcc:             4.8.5-1            r                     
    libpng:             1.6.17-0           r                     
    libsodium:          1.0.3-0                                  
    libtiff:            4.0.6-1                                  
    libxml2:            2.9.2-1            r                     
    markupsafe:         0.23-py27_2                              
    mistune:            0.7.2-py27_1                             
    nb_conda:           1.0.0-py27_0       anaconda-nb-extensions
    nb_conda_kernels:   1.0.0-py27_0       anaconda-nb-extensions
    nbconvert:          4.2.0-py27_0                             
    nbformat:           4.0.1-py27_0                             
    ncurses:            5.9-1              r                     
    notebook:           4.2.0-py27_0                             
    openssl:            1.0.2h-1                                 
    path.py:            8.2.1-py27_0                             
    pathlib2:           2.1.0-py27_0                             
    pcre:               8.31-0                                   
    pexpect:            4.0.1-py27_0                             
    pickleshare:        0.7.2-py27_0                             
    pip:                8.1.1-py27_1                             
    ptyprocess:         0.5.1-py27_0                             
    pygments:           2.1.3-py27_0                             
    pyqt:               4.11.4-py27_2                            
    python:             2.7.11-0                                 
    python.app:         1.2-py27_4                               
    pyzmq:              14.5.0-py27_1      r                     
    qt:                 4.8.7-2                                  
    qtconsole:          4.2.1-py27_0                             
    r:                  3.2.2-0            r                     
    r-base:             3.2.2-0            r                     
    r-boot:             1.3_17-r3.2.2_0a   r                     
    r-class:            7.3_14-r3.2.2_0a   r                     
    r-cluster:          2.0.3-r3.2.2_0a    r                     
    r-codetools:        0.2_14-r3.2.2_0a   r                     
    r-foreign:          0.8_66-r3.2.2_0a   r                     
    r-kernsmooth:       2.23_15-r3.2.2_0a  r                     
    r-lattice:          0.20_33-r3.2.2_0a  r                     
    r-mass:             7.3_45-r3.2.2_0a   r                     
    r-matrix:           1.2_2-r3.2.2_0a    r                     
    r-mgcv:             1.8_9-r3.2.2_0a    r                     
    r-nlme:             3.1_122-r3.2.2_0a  r                     
    r-nnet:             7.3_11-r3.2.2_0a   r                     
    r-recommended:      3.2.2-r3.2.2_0     r                     
    r-rpart:            4.1_10-r3.2.2_0a   r                     
    r-spatial:          7.3_11-r3.2.2_0a   r                     
    r-survival:         2.38_3-r3.2.2_0a   r                     
    readline:           6.2-2                                    
    rpy2:               2.7.0-py27r3.2.2_0 r                     
    setuptools:         21.2.1-py27_0                            
    simplegeneric:      0.8.1-py27_1                             
    singledispatch:     3.4.0.3-py27_1     r                     
    sip:                4.16.9-py27_0                            
    six:                1.10.0-py27_0                            
    sqlite:             3.13.0-0                                 
    ssl_match_hostname: 3.4.0.2-py27_1                           
    terminado:          0.6-py27_0                               
    tk:                 8.5.18-0                                 
    tornado:            4.3-py27_1                               
    traitlets:          4.2.1-py27_0                             
    wheel:              0.29.0-py27_0                            
    xz:                 5.0.5-1                                  
    zeromq:             4.0.5-1            r                     
    zlib:               1.2.8-1            r                     

Proceed ([y]/n)? y

Linking packages ...
[ipython             ]|###########################################################################                                            |  6/Users/ijstokes/anaconda/envs/mro/bin/python: dlopen(/Users/ijstokes/anaconda/envs/mro/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Library not loaded: @rpath/libsodium.4.dylib
  Referenced from: /Users/ijstokes/anaconda/envs/mro/lib/libzmq.4.dylib
  Reason: image not found
Error: Error: post-link failed for: anaconda-nb-extensions::nb_conda_kernels-1.0.0-py27_0
```

**Comment by bollwyvl** [comment] 2016-06-09 05:07
Weird. Could not reproduce, today... Was this on linux or osx?

**Comment by mmarchetti** [comment] 2016-06-09 12:39
Maybe the channel setup is different? @ijstokes, you are getting pyzmq from the r channel instead of the anaconda channel and they are carrying different versions.

**Comment by damianavila** [comment] 2017-04-10 19:50
Old version and I could not see this behavior with the 2.0.0 version. Closing now.

**Closed by damianavila** 2017-04-10 19:50 UTC
