### ISSUE TITLE
Request for tutorial/workaround to install kernelspecs from nb_conda_kernels to jupyter_client

### ISSUE THREAD

**Issue by ruxi** [Anaconda-Platform/nb_conda_kernels#168] opened 2020-07-29 20:44 UTC
```nb_conda_kernels``` dynamically creates ```kernelspecs``` from environments and is managed by ```CondaKernelSpecManager``` but is not installed onto the system.

That's why there is a discrepency between visible notebook kernelspecs and system kernelspecs 

It's not clear how to install the custom ```nb_conda_kernel``` kernelspecs to the system via the ```README.md``` or wiki documentation. Has others been able to do this?

I've been looking into using the following command, but have been running into bugs while testing

```python
import jupyter_client
jupyter_client.kernelspec.install_kernel_spec
```

----

how to list notebook kernelspecs:

```python
import nb_conda_kernels
nb_conda_kernels.CondaKernelSpecManager().find_kernel_specs()
```

how to list system kernelspecs:

```bash
jupyter kenelspec list
```
or 

```python
import jupyter_client
jupyter_client.kernelspec.find_kernel_specs()
```

**Comment by mcg1969** [comment] 2020-08-04 06:57
Closed as duplicate of #77. I'm afraid this is a longstanding, known issue. More info there.

**Closed by mcg1969** 2020-08-04 06:57 UTC
