### ISSUE TITLE
Shell operations should use same Python as kernel

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_conda_kernels#19] opened 2016-04-11 16:06 UTC
We want to avoid this situation:

<img width="1058" alt="screenshot 2016-04-11 11 59 40" src="https://cloud.githubusercontent.com/assets/293525/14433798/b752a7c0-ffdd-11e5-9c61-43098497606b.png">

And my best guess as to how to achieve this would be to update `os.environ['PATH']` to match the selected kernel.

**Comment by ijstokes** [comment] 2016-04-12 16:10
@mmarchetti @damianavila and @bollwyvl can you provide your 2¢ on this issue?  Is there an easy, obvious, and clean solution to this problem?  A size estimate from someone would be appreciated, if it is viewed as "sensible" and "achievable" to do this.

**Comment by ijstokes** [comment] 2016-04-12 16:11
This particularly has impact when people do operations such as
```
!conda install foo
```
since this will install `foo` into the wrong environment.

**Comment by mmarchetti** [comment] 2016-04-12 16:42
I'm not that familiar with the interactive shell, but I wonder if we could set the config variable `InteractiveShellApp.file_to_run` to point to the `.projectrc` file. That would activate the right conda environment (setting PATH among other things) as well as any user-customizations applied there.

**Comment by janschulz** [comment] 2016-04-19 12:14
See also https://github.com/Anaconda-Platform/nb_conda_kernels/issues/17#issuecomment-211880733 and the linked comments.

I don't think `InteractiveShellApp.file_to_run` will be a solution, as this would a) only work in python kernels and not R and b) AFAIS this is executed as a python file and so you would need to duplicate the steps the activate script would do (e.g. especially calling the batch files in `"%CONDA_DEFAULT_ENV%\etc\conda\activate.d` and getting the changes back into the current process).

Any easy solution would be to not call python directly but a batch file which is generated and which does the activate and then `exec` (on linux) the kernel. The problem is that on windows, there is no exec and the jupyter-client has problem killing such kernels if they need to be killed (e.g. when using "restart" when the kernel is unresponsive) -> https://github.com/jupyter/jupyter_client/issues/104

See also See also this issue: https://github.com/jupyter/jupyter_client/issues/127 which discusses some other ways how to setup the environment variables before starting a kernel.

**Comment by damianavila** [comment] 2016-04-20 20:31
I agree `InteractiveShellApp.file_to_run` is probably not an option... because of the things outlined by @janschulz.

From the AEN perspective, I don't see a problem because the user can not `conda install` in the notebook server environment, and they have the conda ab to actually use conda...

This probably need some of the work already outlined by @janschulz in several of the issues he referenced back. 

@ijstokes So... probably this is something to deal with in the future BUT looking how these things evolve and probably not a high priority now compared with other overall priorities (although everyone would like to see it now).

**Comment by parente** [comment] 2016-08-24 13:23
We have a need in our deployment to get this working. I know activating the env via the batch file won't work on Windows, but will you consider a PR that at least fixes it for Linux now?

**Comment by janschulz** [comment] 2016-08-24 14:29
Just FYI: this is now fixed in the https://github.com/Cadair/jupyter_environment_kernels/ and so the solution there should be copyable into this repo.

**Comment by parente** [comment] 2016-08-25 15:27
@janschulz thanks for the pointer. So it looks like porting that solution here would minimally involve duplicating the magic xonsh script that dumps env vars, and getting those env vars into the kernel spec params.

**Comment by janschulz** [comment] 2016-08-25 16:21
If this shouldn't be a performance hog at startup time, it also needs to pull in the [lazyobj](https://github.com/Cadair/jupyter_environment_kernels/blob/master/environment_kernels/lazyobj.py) file and usage...

**Comment by mcg1969** [comment] 2018-08-24 17:52
This is fixed by #80.

**Closed by mcg1969** 2018-08-24 17:52 UTC
Labels: enhancement
