### ISSUE TITLE
nb_conda_kernels does not discover kernels anymore

### ISSUE THREAD

**Issue by gyger** [Anaconda-Platform/nb_conda_kernels#74] opened 2018-01-23 10:26 UTC
After upgrading jupyter in anaconda to 5.3.1, the extension fails with the error like this for every discovered kernel:

[W 11:22:56.453 NotebookApp] Error loading kernelspec 'conda-env-qutip-py'
    Traceback (most recent call last):
      File "C:\Users\user\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\Users\user\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\Users\user\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'

See also the bug posted to jupyter, but I guess it is an extension error.
https://github.com/jupyter/notebook/issues/3241

**Comment by dartdog** [comment] 2018-01-23 19:20
cross referencing https://github.com/jupyter/jupyter_client/issues/338

**Comment by michaelaye** [comment] 2018-01-23 19:41
Duplicate of #73 ?

**Comment by gyger** [comment] 2018-01-24 20:04
I am not sure, but I do not think so, I see a completely different stacktrace.

**Comment by dartdog** [comment] 2018-01-24 21:12
I'm pretty sure we had the same trace on the id'd Jupyter issue, 5.3.2 should be out soon

**Comment by gyger** [comment] 2018-01-24 21:17
@dartdog Yes, I think the one you referenced is the correct issue. I was more wondering about the comment of #73.

**Comment by mcg1969** [comment] 2018-08-24 17:34
I'm reasonably certain #80 is going to fix this, because it completely changes how kernels are found. So let's close and re-open as necessary.

**Closed by mcg1969** 2018-08-24 17:34 UTC
